### PR TITLE
Vector tiles updates

### PR DESCRIPTION
**Pull request by Rub21**
From: https://github.com/OpenHistoricalMap/issues/issues/461 and https://github.com/OpenHistoricalMap/issues/issues/463

cc. @tsinn

### CODE REVIEW

**Comment by danrademacher** [comment]
Hmm, I didn't realize this was still awaiting merge. The test of deploying iD onto staging now makes this PR unmergeable, since that will break iD on the live site

**Comment by geohacker** [comment]
@danrademacher @Rub21 with this PR iD changes are all ready to be released to production. I've also created the oauth2 application on production and supplied the necessary Github secret. I will wait to merge until you both have had a chance to confirm that this is ready to go.

**Comment by Rub21** [comment]
@geohacker , This is ready for merging into main,  if everything is ready from Dan side, we could merge tomorrow when i get online.

**Comment by danrademacher** [comment]
I just tested iD on staging and this looks ready to me. Please deploy at the next opportunity. Thanks!

**Pull request merged**
